---
title: "Generative AI"
author: ir. Louis Verschuren, ir. Olivier Bonte  
---

Wat betreft het gebruik van (generatieve) AI:

- Toegelaten tot op zekere hoogte voor het helpen bij het schrijven van code (niet om je code volledig automatisch te laten genereren) via *code completion*, maar je dient correct weer te geven, per verslag, waar en hoe je ervan gebruik gemaakt hebt (websites, tools, welke prompt engineering, etc) 
- Het is eveneens belangrijk je bevindingen te vermelden in verband met de juistheid / accuraatheid bij het gebruik van deze (generatieve) AI. Een kritische blik is van het grootste belang en wordt dan ook verwacht. 
- Het is niet toegelaten grote stukken van of een volledig verslag te laten genereren door (generatieve) AI Op die manier ben jij namelijk niet meer de auteur van het werk. Zie ook het OER van de UGent 
- Je blijft verantwoordelijk voor alles wat de genAI tools genereren (plagiaat!) 
- Het is niet toegelaten (stukken van) de cursus aan eender welke (generatieve) AI aan te bieden 
- Wees je ervan bewust dat het gebruik van AI een impact heeft op je eigen skills 
- Wees bewust van de ecologische voetafdruk^[Dit [VN rapport](https://doi.org/10.53328/INR26RMA002) geeft interestante achtergrondinformatie hierover] van het gebruik van GenAI
- Je wordt verwacht de eindcompetenties te beheersen 
- Je moet je code begrijpen en kunnen toelichten 

Zie ook het [Universiteitsbreed ricthkader voor het verantwoord gebruik van AI aan de UGent](https://www.ugent.be/nl/univgent/missie/genai/richtkader-verantwoord-ai-gebruik)  